### ISSUE TITLE
generating some sql create tables with xsd

### ISSUE THREAD

**Issue by ElianoMarques** [ricksladkey/generateDS#2]
Hi, hope you can help me here. 

I have some .xsd files where im trying to convert them to sql. 

Do you know if it will be possible to do so leveraging the generateDS package? 

Thank you, 
Eliano

**Comment by ricksladkey** [comment]
I do not think so, but you should realize that this project is only a port of GenerateDS, not the original. Furthermore, the original has been ported itself, so this project is obsolete.

I recommend you pursue your questions over at:

https://www.davekuhlman.org/generateDS.html
